### PR TITLE
Add web illustration

### PR DESCRIPTION
**Pull request by aninternetof**
This is @ccLouis's wonderful work on the new homepage!

He has added illustrations, improved the styling, and reorganized our CSS to be better structured.

Live preview: https://rovercode-marketing-homepage-preview.netlify.com/

Let @ccLouis know here what feedback you have!

### CODE REVIEW

**Comment by ductape** [comment]
screen shot 2018-10-24 at 11 16 47 am
I think my CSS might be messed up... is this the intended look? The site looks the same on Chrome 70.0.3538.67, Firefox 63.0, and Safari 11.1.1 on OS X 10.13.5.

**Comment by aninternetof** [comment]
> screen shot 2018-10-24 at 11 16 47 am
> I think my CSS might be messed up... is this the intended look? The site looks the same on Chrome 70.0.3538.67, Firefox 63.0, and Safari 11.1.1 on OS X 10.13.5.

Hi Shaun -- did you run the `yarn install`? That should add the Semantic UI CSS that it needs to look right.
If you did, let me know, and we can keep debugging.

**Comment by aninternetof** [comment]
Maybe I'll throw this branch on a quick Netlify deploy so not everyone needs to get it running...
I'll look into it after lunch.

**Comment by aninternetof** [comment]
Here is a live preview of it so your don't have to get it running yourself! https://rovercode-marketing-homepage-preview.netlify.com/

**Comment by aninternetof** [comment]
The logo you used here has really grown on me. I think it's a great way to go.

**Comment by ccLouis** [comment]
Spending some time today mapping out and adjusting the logo again. 

I'll add exporting a placeholder favicon on my todos.

Cheers for the responses so far.

**Pull request merged**
